import json, re

periodic_table = json.load(open('periodic_table.json'))

input = 'CrCoRaLiBhMnMdSmNhPbCaUUMoIrPoEuCPmPoRbPuOsLrArCmPdCeNBkBaLaCuAsCfPrCdBaNdAlAlRuBaTlFlUueTsRnCeCrHfPmLaPbMdCfBrBkPrGdEsUCfNeMgSmLaBhLuDsMoSmAlOPbDbCuCeEsEsXeCaMdHeSbLvThAtFRuNbPrLiCuLaNiYbMdClArPmAcTmGdAtLvSrNdScTmFMgUueTsPdBrSmRuOTeAcLuHsTmUueYbMnCHfDyPbRaSePmHfAlKNYHgPrXeWHTsAtHsGeAsRfPoTlSMoLvHgMcRuCTsLrHsPoRhYbAsErTmITiAlSgNFVNpCuCdSmAtFeNdGaFLiBrInBhOsEuNbLiIrFlMoFlCuLaMcKSeNiCdCmAsSSeTmFrPoNiTeSrMoErPtNoVInGdTmTiOsPrBhCmAmOSgSrSrTeNaScSiErRbPrTeClPoArSmArLuSnSrAuPHfTaNpOgArCnDyLaSmCoSbSiBhTbTbCmSErYbCoBhEsCaErHoHeAlTsClRaBeRbReHoTmSnTcGdBkFeNpCaNiNoTlMgMgLaNbNiAtMtRaNbOgClDsKrHeTbRaPCdNLiPdBrZnZnBkSiICeBiBiKBErFrBkXeZnGdErNeRgGaRgHeRgFmCnTlHgGaNbNhPdLrKNaKrCnAmErGeGdThTmCSeRgBhDbDyWCfSmFlBNeOBkPmUuePrCnCeTiBkFUueCdOYbYbLiEuEsBkHgGdLiMcNpYHfClFeMtCaXeNiErRgHoNiTbRaICuTmMgCoMgCdBhCeCnNeUArFrVErRhAuNpNpNpGeCnLvLaSrIrLuCfYbFlAcUCfInBSbAmSrBrCoVSiInSmOsTePtMoRfZnTaHPdSeAuVAsHgTeXeMgNbUueMtYDbOGdKrXeFmFHfRnHeMoDsCnMtOsBiPoSrNPdRgKrKKrHfF'

a = re.sub('([a-z])?([A-Z])', r'\1 \2', input).split()

print(''.join([periodic_table[elem] for elem in a]))